// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using miniJob.Services.Database;

#nullable disable

namespace miniJob.Services.Migrations
{
    [DbContext(typeof(miniJobsContext))]
    partial class miniJobsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("miniJob.Services.Database.ApliciraniPosao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AplikantId")
                        .HasColumnType("int")
                        .HasColumnName("aplikant_id");

                    b.Property<DateTime>("DatumApliciranja")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_apliciranja");

                    b.Property<int>("PosaoId")
                        .HasColumnType("int")
                        .HasColumnName("posao_id");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AplikantId" }, "IX_ApliciraniPosao_aplikant_id");

                    b.HasIndex(new[] { "PosaoId" }, "IX_ApliciraniPosao_posao_id");

                    b.ToTable("ApliciraniPosao", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.Aplikant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Cv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CV");

                    b.Property<string>("Iskustvo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("iskustvo");

                    b.Property<string>("NivoObrazovanja")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nivoObrazovanja");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("opis");

                    b.Property<int?>("OpstinaRodjenjaId")
                        .HasColumnType("int")
                        .HasColumnName("opstina_rodjenja_id");

                    b.Property<int?>("PreporukaId")
                        .HasColumnType("int")
                        .HasColumnName("preporuka_id");

                    b.Property<int?>("PrijedlogSatince")
                        .HasColumnType("int")
                        .HasColumnName("prijedlogSatince");

                    b.Property<string>("Slika")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("slika");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OpstinaRodjenjaId" }, "IX_Aplikant_opstina_rodjenja_id");

                    b.HasIndex(new[] { "PreporukaId" }, "IX_Aplikant_preporuka_id");

                    b.ToTable("Aplikant", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.AplikantPosaoTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AplikantId")
                        .HasColumnType("int")
                        .HasColumnName("aplikant_id");

                    b.Property<int?>("Aplikantid1")
                        .HasColumnType("int")
                        .HasColumnName("aplikantid");

                    b.Property<int>("PosaoTipId")
                        .HasColumnType("int")
                        .HasColumnName("posaoTip_id");

                    b.Property<int?>("PosaoTipid1")
                        .HasColumnType("int")
                        .HasColumnName("posaoTipid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Aplikantid1" }, "IX_aplikantPosaoTip_aplikantid");

                    b.HasIndex(new[] { "PosaoTipid1" }, "IX_aplikantPosaoTip_posaoTipid");

                    b.ToTable("aplikantPosaoTip", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.Drzava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("naziv");

                    b.HasKey("Id");

                    b.ToTable("Drzava", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.KorisnickiNalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("brojTelefona");

                    b.Property<DateTime?>("DatumRegistracije")
                        .HasColumnType("datetime2")
                        .HasColumnName("datumRegistracije");

                    b.Property<string>("DatumRodjenja")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("datumRodjenja");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailPotvrđen")
                        .HasColumnType("bit")
                        .HasColumnName("emailPotvrđen");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("isAdmin");

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("korisnickoIme");

                    b.Property<string>("LozinkaHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lozinkaHash");

                    b.Property<string>("LozinkaSalt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lozinkaSalt");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("refreshToken");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("refreshTokenExpiryTime");

                    b.Property<string>("SlikaKorisnika")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("slika_korisnika");

                    b.Property<string>("Spol")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("spol");

                    b.Property<int?>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.ToTable("KorisnickiNalog", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.Ocjena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApliciraniPosaoId")
                        .HasColumnType("int")
                        .HasColumnName("apliciraniPosao_id");

                    b.Property<string>("Komentar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("komentar");

                    b.Property<int>("OcjenjenId")
                        .HasColumnType("int")
                        .HasColumnName("ocjenjen_id");

                    b.Property<int?>("Ocjenjenid1")
                        .HasColumnType("int")
                        .HasColumnName("ocjenjenid");

                    b.Property<int>("OcjenjujeId")
                        .HasColumnType("int")
                        .HasColumnName("ocjenjuje_id");

                    b.Property<int>("Vrijednost")
                        .HasColumnType("int")
                        .HasColumnName("vrijednost");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ApliciraniPosaoId" }, "IX_Ocjena_apliciraniPosao_id");

                    b.HasIndex(new[] { "Ocjenjenid1" }, "IX_Ocjena_ocjenjenid");

                    b.HasIndex(new[] { "OcjenjujeId" }, "IX_Ocjena_ocjenjuje_id");

                    b.ToTable("Ocjena", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.Opstina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("DrzavaId")
                        .HasColumnType("int")
                        .HasColumnName("drzava_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DrzavaId" }, "IX_Opstina_drzava_id");

                    b.ToTable("Opstina", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.Pitanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("naziv");

                    b.HasKey("Id");

                    b.ToTable("Pitanje", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.PitanjeOdgovor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PonudjeniOdgovorId")
                        .HasColumnType("int")
                        .HasColumnName("ponudjeniOdgovor_id");

                    b.Property<int>("PosaoPitanjeId")
                        .HasColumnType("int")
                        .HasColumnName("posaoPitanje_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PonudjeniOdgovorId" }, "IX_PitanjeOdgovor_ponudjeniOdgovor_id");

                    b.HasIndex(new[] { "PosaoPitanjeId" }, "IX_PitanjeOdgovor_posaoPitanje_id");

                    b.ToTable("PitanjeOdgovor", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.PonudjeniOdgovor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Odgovor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("odgovor");

                    b.Property<int>("PitanjeId")
                        .HasColumnType("int")
                        .HasColumnName("pitanje_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PitanjeId" }, "IX_PonudjeniOdgovor_pitanje_id");

                    b.ToTable("PonudjeniOdgovor", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.Posao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("adresa");

                    b.Property<int>("BrojAplikanata")
                        .HasColumnType("int")
                        .HasColumnName("brojAplikanata");

                    b.Property<int>("Cijena")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2")
                        .HasColumnName("datum_kreiranja");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2")
                        .HasColumnName("deadline");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("naziv");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("opis");

                    b.Property<int>("OpstinaId")
                        .HasColumnType("int")
                        .HasColumnName("opstina_id");

                    b.Property<int>("PosaoTipId")
                        .HasColumnType("int")
                        .HasColumnName("posaoTip_id");

                    b.Property<int>("PoslodavacId")
                        .HasColumnType("int")
                        .HasColumnName("poslodavac_id");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OpstinaId" }, "IX_Posao_opstina_id");

                    b.HasIndex(new[] { "PosaoTipId" }, "IX_Posao_posaoTip_id");

                    b.HasIndex(new[] { "PoslodavacId" }, "IX_Posao_poslodavac_id");

                    b.ToTable("Posao", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.PosaoPitanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PitanjeId")
                        .HasColumnType("int")
                        .HasColumnName("pitanje_id");

                    b.Property<int>("PosaoId")
                        .HasColumnType("int")
                        .HasColumnName("posao_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PitanjeId" }, "IX_PosaoPitanje_pitanje_id");

                    b.HasIndex(new[] { "PosaoId" }, "IX_PosaoPitanje_posao_id");

                    b.ToTable("PosaoPitanje", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.PosaoTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("naziv");

                    b.HasKey("Id");

                    b.ToTable("PosaoTip", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.Poslodavac", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("adresa");

                    b.Property<string>("NazivFirme")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Poslodavac", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.Preporuka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OpstinaId")
                        .HasColumnType("int")
                        .HasColumnName("opstina_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OpstinaId" }, "IX_Preporuka_opstina_id");

                    b.ToTable("Preporuka", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.PreporukaTipPosla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PosaoTipId")
                        .HasColumnType("int")
                        .HasColumnName("posaoTip_id");

                    b.Property<int>("PreporukaId")
                        .HasColumnType("int")
                        .HasColumnName("preporuka_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PosaoTipId" }, "IX_PreporukaTipPosla_posaoTip_id");

                    b.HasIndex(new[] { "PreporukaId" }, "IX_PreporukaTipPosla_preporuka_id");

                    b.ToTable("PreporukaTipPosla", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.SpremljeniPosao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AplikantId")
                        .HasColumnType("int")
                        .HasColumnName("aplikant_id");

                    b.Property<int>("PosaoId")
                        .HasColumnType("int")
                        .HasColumnName("posao_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AplikantId" }, "IX_SpremljeniPosao_aplikant_id");

                    b.HasIndex(new[] { "PosaoId" }, "IX_SpremljeniPosao_posao_id");

                    b.ToTable("SpremljeniPosao", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.VerifikacijaEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int")
                        .HasColumnName("korisnik_id");

                    b.Property<int>("VerifikaciskiKod")
                        .HasColumnType("int")
                        .HasColumnName("verifikaciskiKod");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "KorisnikId" }, "IX_verifikacijaEmail_korisnik_id");

                    b.ToTable("verifikacijaEmail", (string)null);
                });

            modelBuilder.Entity("miniJob.Services.Database.ApliciraniPosao", b =>
                {
                    b.HasOne("miniJob.Services.Database.Aplikant", "Aplikant")
                        .WithMany("ApliciraniPosaos")
                        .HasForeignKey("AplikantId")
                        .IsRequired();

                    b.HasOne("miniJob.Services.Database.Posao", "Posao")
                        .WithMany("ApliciraniPosaos")
                        .HasForeignKey("PosaoId")
                        .IsRequired();

                    b.Navigation("Aplikant");

                    b.Navigation("Posao");
                });

            modelBuilder.Entity("miniJob.Services.Database.Aplikant", b =>
                {
                    b.HasOne("miniJob.Services.Database.KorisnickiNalog", "IdNavigation")
                        .WithOne("Aplikant")
                        .HasForeignKey("miniJob.Services.Database.Aplikant", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("miniJob.Services.Database.Opstina", "OpstinaRodjenja")
                        .WithMany("Aplikants")
                        .HasForeignKey("OpstinaRodjenjaId");

                    b.HasOne("miniJob.Services.Database.Preporuka", "Preporuka")
                        .WithMany("Aplikants")
                        .HasForeignKey("PreporukaId");

                    b.Navigation("IdNavigation");

                    b.Navigation("OpstinaRodjenja");

                    b.Navigation("Preporuka");
                });

            modelBuilder.Entity("miniJob.Services.Database.AplikantPosaoTip", b =>
                {
                    b.HasOne("miniJob.Services.Database.Aplikant", "Aplikantid1Navigation")
                        .WithMany("AplikantPosaoTips")
                        .HasForeignKey("Aplikantid1");

                    b.HasOne("miniJob.Services.Database.PosaoTip", "PosaoTipid1Navigation")
                        .WithMany("AplikantPosaoTips")
                        .HasForeignKey("PosaoTipid1");

                    b.Navigation("Aplikantid1Navigation");

                    b.Navigation("PosaoTipid1Navigation");
                });

            modelBuilder.Entity("miniJob.Services.Database.Ocjena", b =>
                {
                    b.HasOne("miniJob.Services.Database.ApliciraniPosao", "ApliciraniPosao")
                        .WithMany("Ocjenas")
                        .HasForeignKey("ApliciraniPosaoId")
                        .IsRequired();

                    b.HasOne("miniJob.Services.Database.KorisnickiNalog", "Ocjenjenid1Navigation")
                        .WithMany("OcjenaOcjenjenid1Navigations")
                        .HasForeignKey("Ocjenjenid1");

                    b.HasOne("miniJob.Services.Database.KorisnickiNalog", "Ocjenjuje")
                        .WithMany("OcjenaOcjenjujes")
                        .HasForeignKey("OcjenjujeId")
                        .IsRequired();

                    b.Navigation("ApliciraniPosao");

                    b.Navigation("Ocjenjenid1Navigation");

                    b.Navigation("Ocjenjuje");
                });

            modelBuilder.Entity("miniJob.Services.Database.Opstina", b =>
                {
                    b.HasOne("miniJob.Services.Database.Drzava", "Drzava")
                        .WithMany("Opstinas")
                        .HasForeignKey("DrzavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drzava");
                });

            modelBuilder.Entity("miniJob.Services.Database.PitanjeOdgovor", b =>
                {
                    b.HasOne("miniJob.Services.Database.PonudjeniOdgovor", "PonudjeniOdgovor")
                        .WithMany("PitanjeOdgovors")
                        .HasForeignKey("PonudjeniOdgovorId")
                        .IsRequired();

                    b.HasOne("miniJob.Services.Database.PosaoPitanje", "PosaoPitanje")
                        .WithMany("PitanjeOdgovors")
                        .HasForeignKey("PosaoPitanjeId")
                        .IsRequired();

                    b.Navigation("PonudjeniOdgovor");

                    b.Navigation("PosaoPitanje");
                });

            modelBuilder.Entity("miniJob.Services.Database.PonudjeniOdgovor", b =>
                {
                    b.HasOne("miniJob.Services.Database.Pitanje", "Pitanje")
                        .WithMany("PonudjeniOdgovors")
                        .HasForeignKey("PitanjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pitanje");
                });

            modelBuilder.Entity("miniJob.Services.Database.Posao", b =>
                {
                    b.HasOne("miniJob.Services.Database.Opstina", "Opstina")
                        .WithMany("Posaos")
                        .HasForeignKey("OpstinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("miniJob.Services.Database.PosaoTip", "PosaoTip")
                        .WithMany("Posaos")
                        .HasForeignKey("PosaoTipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("miniJob.Services.Database.Poslodavac", "Poslodavac")
                        .WithMany("Posaos")
                        .HasForeignKey("PoslodavacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opstina");

                    b.Navigation("PosaoTip");

                    b.Navigation("Poslodavac");
                });

            modelBuilder.Entity("miniJob.Services.Database.PosaoPitanje", b =>
                {
                    b.HasOne("miniJob.Services.Database.Pitanje", "Pitanje")
                        .WithMany("PosaoPitanjes")
                        .HasForeignKey("PitanjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("miniJob.Services.Database.Posao", "Posao")
                        .WithMany("PosaoPitanjes")
                        .HasForeignKey("PosaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pitanje");

                    b.Navigation("Posao");
                });

            modelBuilder.Entity("miniJob.Services.Database.Poslodavac", b =>
                {
                    b.HasOne("miniJob.Services.Database.KorisnickiNalog", "IdNavigation")
                        .WithOne("Poslodavac")
                        .HasForeignKey("miniJob.Services.Database.Poslodavac", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("miniJob.Services.Database.Preporuka", b =>
                {
                    b.HasOne("miniJob.Services.Database.Opstina", "Opstina")
                        .WithMany("Preporukas")
                        .HasForeignKey("OpstinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opstina");
                });

            modelBuilder.Entity("miniJob.Services.Database.PreporukaTipPosla", b =>
                {
                    b.HasOne("miniJob.Services.Database.PosaoTip", "PosaoTip")
                        .WithMany("PreporukaTipPoslas")
                        .HasForeignKey("PosaoTipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("miniJob.Services.Database.Preporuka", "Preporuka")
                        .WithMany("PreporukaTipPoslas")
                        .HasForeignKey("PreporukaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PosaoTip");

                    b.Navigation("Preporuka");
                });

            modelBuilder.Entity("miniJob.Services.Database.SpremljeniPosao", b =>
                {
                    b.HasOne("miniJob.Services.Database.Aplikant", "Aplikant")
                        .WithMany("SpremljeniPosaos")
                        .HasForeignKey("AplikantId")
                        .IsRequired();

                    b.HasOne("miniJob.Services.Database.Posao", "Posao")
                        .WithMany("SpremljeniPosaos")
                        .HasForeignKey("PosaoId")
                        .IsRequired();

                    b.Navigation("Aplikant");

                    b.Navigation("Posao");
                });

            modelBuilder.Entity("miniJob.Services.Database.VerifikacijaEmail", b =>
                {
                    b.HasOne("miniJob.Services.Database.KorisnickiNalog", "Korisnik")
                        .WithMany("VerifikacijaEmails")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("miniJob.Services.Database.ApliciraniPosao", b =>
                {
                    b.Navigation("Ocjenas");
                });

            modelBuilder.Entity("miniJob.Services.Database.Aplikant", b =>
                {
                    b.Navigation("ApliciraniPosaos");

                    b.Navigation("AplikantPosaoTips");

                    b.Navigation("SpremljeniPosaos");
                });

            modelBuilder.Entity("miniJob.Services.Database.Drzava", b =>
                {
                    b.Navigation("Opstinas");
                });

            modelBuilder.Entity("miniJob.Services.Database.KorisnickiNalog", b =>
                {
                    b.Navigation("Aplikant");

                    b.Navigation("OcjenaOcjenjenid1Navigations");

                    b.Navigation("OcjenaOcjenjujes");

                    b.Navigation("Poslodavac");

                    b.Navigation("VerifikacijaEmails");
                });

            modelBuilder.Entity("miniJob.Services.Database.Opstina", b =>
                {
                    b.Navigation("Aplikants");

                    b.Navigation("Posaos");

                    b.Navigation("Preporukas");
                });

            modelBuilder.Entity("miniJob.Services.Database.Pitanje", b =>
                {
                    b.Navigation("PonudjeniOdgovors");

                    b.Navigation("PosaoPitanjes");
                });

            modelBuilder.Entity("miniJob.Services.Database.PonudjeniOdgovor", b =>
                {
                    b.Navigation("PitanjeOdgovors");
                });

            modelBuilder.Entity("miniJob.Services.Database.Posao", b =>
                {
                    b.Navigation("ApliciraniPosaos");

                    b.Navigation("PosaoPitanjes");

                    b.Navigation("SpremljeniPosaos");
                });

            modelBuilder.Entity("miniJob.Services.Database.PosaoPitanje", b =>
                {
                    b.Navigation("PitanjeOdgovors");
                });

            modelBuilder.Entity("miniJob.Services.Database.PosaoTip", b =>
                {
                    b.Navigation("AplikantPosaoTips");

                    b.Navigation("Posaos");

                    b.Navigation("PreporukaTipPoslas");
                });

            modelBuilder.Entity("miniJob.Services.Database.Poslodavac", b =>
                {
                    b.Navigation("Posaos");
                });

            modelBuilder.Entity("miniJob.Services.Database.Preporuka", b =>
                {
                    b.Navigation("Aplikants");

                    b.Navigation("PreporukaTipPoslas");
                });
#pragma warning restore 612, 618
        }
    }
}
