version: '3.8'

volumes:
  sql_data:

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    hostname: rabbitmq
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "8050:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    networks:
      - miniJobs_network

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sql_server_db
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=Word5678?
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S db -U sa -P $SA_PASSWORD -Q 'SELECT 1;'"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 60s
    networks:
      - miniJobs_network
    volumes:
      - sql_data:/var/opt/mssql
      - ./Infrastructure/Persistence/Migrations/InitialDataScripts:/docker-entrypoint-initdb.d/
    depends_on:
      - rabbitmq

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webapi_container
    restart: unless-stopped
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=miniJobs;User=sa;Password=Word5678?;TrustServerCertificate=True;Encrypt=False;
      - ConnectionStrings__DefaultConnectionHangfire=Server=db,1433;Database=miniJobs_hangfire;User=sa;Password=Word5678?;TrustServerCertificate=True;Encrypt=False;
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_URLS=http://+:7126
    ports:
      - "7126:7126"
    networks:
      - miniJobs_network
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./Infrastructure/Persistence/Migrations/InitialDataScripts:/app/Infrastructure/Persistence/Migrations/InitialDataScripts

  subscriber:
    restart: unless-stopped
    build:
      context: .
      dockerfile: SubscriberService/Dockerfile
    container_name: subscriber_container
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - EMAILSENDER_PROVIDER_EMAIL=smtp.gmail.com
      - EMAILSENDER_PORT=587
      - EMAILSENDER_MAIL_ADDRESS=minijobs2023@gmail.com
      - EMAILSENDER_KEY=mqpeirblrthovtjd
    depends_on:
      - rabbitmq
    networks:
      - miniJobs_network


networks:
  miniJobs_network:
    driver: bridge