//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Localization.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACCOUNT_NOT_APPROVED {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_APPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACCOUNT_NOT_VALID {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ACTION_NOT_POSSIBLE_IN_THIS_JOB_STATUS {
            get {
                return ResourceManager.GetString("ACTION_NOT_POSSIBLE_IN_THIS_JOB_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ADDRESS_IS_REQUIRED {
            get {
                return ResourceManager.GetString("ADDRESS_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ALREADY_APPLIED {
            get {
                return ResourceManager.GetString("ALREADY_APPLIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ALREADY_RATED {
            get {
                return ResourceManager.GetString("ALREADY_RATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ANSWERS_TO_PAYMENT_QUESTIONS_IS_REQUIRED {
            get {
                return ResourceManager.GetString("ANSWERS_TO_PAYMENT_QUESTIONS_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string APPLICANT_NOT_EXISTS {
            get {
                return ResourceManager.GetString("APPLICANT_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string APPLICATIONS_DURATION_IS_REQUIRED {
            get {
                return ResourceManager.GetString("APPLICATIONS_DURATION_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string APPLICATIONS_DURATION_MUST_BE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("APPLICATIONS_DURATION_MUST_BE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AUTH_CODE_IS_MISSING {
            get {
                return ResourceManager.GetString("AUTH_CODE_IS_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AUTH_CODE_NOT_VALID {
            get {
                return ResourceManager.GetString("AUTH_CODE_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BAD_REQUEST {
            get {
                return ResourceManager.GetString("BAD_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CAN_NOT_APPLY_TO_JOB_IN_THIS_STATUS {
            get {
                return ResourceManager.GetString("CAN_NOT_APPLY_TO_JOB_IN_THIS_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CAN_NOT_UPDATE_JOB_IN_THIS_STATUS {
            get {
                return ResourceManager.GetString("CAN_NOT_UPDATE_JOB_IN_THIS_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CITY_IS_REQUIRED {
            get {
                return ResourceManager.GetString("CITY_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CITY_NOT_EXIST {
            get {
                return ResourceManager.GetString("CITY_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string COMPANY_PHONE_NUMBER_IS_REQUIRED {
            get {
                return ResourceManager.GetString("COMPANY_PHONE_NUMBER_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DESCRIPTION_IS_REQUIRED {
            get {
                return ResourceManager.GetString("DESCRIPTION_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EACH_PAYMENT_QUESTION_MUST_HAVE_AT_LEAST_ONE_ANSWER {
            get {
                return ResourceManager.GetString("EACH_PAYMENT_QUESTION_MUST_HAVE_AT_LEAST_ONE_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EMAIL_ADDRESS_EXIST {
            get {
                return ResourceManager.GetString("EMAIL_ADDRESS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EMAIL_IS_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EMPOLOYER_NOT_EXISTS {
            get {
                return ResourceManager.GetString("EMPOLOYER_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FIRST_NAME_IS_REQUIRED {
            get {
                return ResourceManager.GetString("FIRST_NAME_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GENDER_IS_REQUIRED {
            get {
                return ResourceManager.GetString("GENDER_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ID_NUMBER_IS_REQUIRED {
            get {
                return ResourceManager.GetString("ID_NUMBER_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IT_IS_NOT_POSSIBLE_TO_SAVE_JOB {
            get {
                return ResourceManager.GetString("IT_IS_NOT_POSSIBLE_TO_SAVE_JOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_APPLICATION_ALREADY_ACCEPTED {
            get {
                return ResourceManager.GetString("JOB_APPLICATION_ALREADY_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_APPLICATION_ALREADY_REJECTED {
            get {
                return ResourceManager.GetString("JOB_APPLICATION_ALREADY_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_APPLICATION_CAN_NOT_BE_DELETED {
            get {
                return ResourceManager.GetString("JOB_APPLICATION_CAN_NOT_BE_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_APPLICATION_IS_DELETED {
            get {
                return ResourceManager.GetString("JOB_APPLICATION_IS_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_APPLICATION_NOT_EXISTS {
            get {
                return ResourceManager.GetString("JOB_APPLICATION_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_IS_ALREADY_SAVED {
            get {
                return ResourceManager.GetString("JOB_IS_ALREADY_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_IS_COMPLETED {
            get {
                return ResourceManager.GetString("JOB_IS_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_IS_NOT_SAVED {
            get {
                return ResourceManager.GetString("JOB_IS_NOT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_NEED_ACCEPTED_APPLICANTS {
            get {
                return ResourceManager.GetString("JOB_NEED_ACCEPTED_APPLICANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_NOT_COMPLETED {
            get {
                return ResourceManager.GetString("JOB_NOT_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_NOT_EXIST {
            get {
                return ResourceManager.GetString("JOB_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_RECOMMENDATION_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("JOB_RECOMMENDATION_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_RECOMMENDATION_NEED_TO_HAVE_AT_LEAST_ONE_CITY_OR_JOB_TYPE {
            get {
                return ResourceManager.GetString("JOB_RECOMMENDATION_NEED_TO_HAVE_AT_LEAST_ONE_CITY_OR_JOB_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_RECOMMENDATION_NOT_EXISTS {
            get {
                return ResourceManager.GetString("JOB_RECOMMENDATION_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_SCHEDULE_ANSWERS_CANNOT_BE_EMPTY {
            get {
                return ResourceManager.GetString("JOB_SCHEDULE_ANSWERS_CANNOT_BE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_SCHEDULE_IS_REQUIRED {
            get {
                return ResourceManager.GetString("JOB_SCHEDULE_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_SCHEDULE_QUESTION_ID_MUST_BE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("JOB_SCHEDULE_QUESTION_ID_MUST_BE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_TYPE_IS_REQUIRED {
            get {
                return ResourceManager.GetString("JOB_TYPE_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JOB_TYPE_NOT_EXISTS {
            get {
                return ResourceManager.GetString("JOB_TYPE_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LAST_NAME_IS_REQUIRED {
            get {
                return ResourceManager.GetString("LAST_NAME_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NAME_IS_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NOT_ALLOWED_TO_RATE {
            get {
                return ResourceManager.GetString("NOT_ALLOWED_TO_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NOT_VALID_STRING_LENGHT {
            get {
                return ResourceManager.GetString("NOT_VALID_STRING_LENGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PASSWORD_IS_REQUIRED {
            get {
                return ResourceManager.GetString("PASSWORD_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PHONE_NUMBER_IS_REQUIRED {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PHOTO_NUMBER_IS_REQUIRED {
            get {
                return ResourceManager.GetString("PHOTO_NUMBER_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QUESTION_NOT_EXIST {
            get {
                return ResourceManager.GetString("QUESTION_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string REQUIRED_EMPLOYEES_IS_REQUIRED {
            get {
                return ResourceManager.GetString("REQUIRED_EMPLOYEES_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string REQUIRED_EMPLOYEES_MUST_BE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("REQUIRED_EMPLOYEES_MUST_BE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string STREETADDRESSANDNUMBER_IS_REQUIRED {
            get {
                return ResourceManager.GetString("STREETADDRESSANDNUMBER_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string USERNAME_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("USERNAME_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WAGE_IS_REQUIRED {
            get {
                return ResourceManager.GetString("WAGE_IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WAGE_MUST_BE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("WAGE_MUST_BE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
    }
}
