INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Novi Travnik','72290', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Srednjobosanski kanton'),'065');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Jajce','70101', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Srednjobosanski kanton'),'042');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Bugojno','70230', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Srednjobosanski kanton'),'017');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Travnik','72270', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Srednjobosanski kanton'),'091');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Busovača','72260', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Srednjobosanski kanton'),'018');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Donji Vakuf','70220', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Srednjobosanski kanton'),'026');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Kiseljak','71250', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Srednjobosanski kanton'),'046');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Kreševo','71260', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Srednjobosanski kanton'),'051');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Fojnica','71270', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Srednjobosanski kanton'),'030');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Vitez','72250', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Srednjobosanski kanton'),'100');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Gornji Vakuf-Uskoplje','70240', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Srednjobosanski kanton'),'034');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Dobretići','77210', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Srednjobosanski kanton'),'050');

INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Bihać','77000', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Unsko-sanski kanton'),'003');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Bosanska Krupa','77240', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Unsko-sanski kanton'),'008');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Bosanski Petrovac','77250', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Unsko-sanski kanton'),'011');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Cazin','77220', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Unsko-sanski kanton'),'019');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Ključ','79280', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Unsko-sanski kanton'),'048');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Sanski Most','79260', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Unsko-sanski kanton'),'076');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Velika Kladuša','77230', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Unsko-sanski kanton'),'097');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Bužim','77245', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Unsko-sanski kanton'),'124');


INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Orašje','76270', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Posavski kanton'),'068');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Odžak','76290', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Posavski kanton'),'066');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Domaljevac-Šamac','76233', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Posavski kanton'),'012');

INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Banovići','75290', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Tuzlanski kanton'),'001');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Gračanica','75320', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Tuzlanski kanton'),'035');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Gradačac','76250', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Tuzlanski kanton'),'036');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Kalesija','75260', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Tuzlanski kanton'),'044');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Kladanj','75280', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Tuzlanski kanton'),'047');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Čelić','75246', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Tuzlanski kanton'),'056');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Lukavac','75300', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Tuzlanski kanton'),'057');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Srebrenik','75350', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Tuzlanski kanton'),'085');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Tuzla','75000', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Tuzlanski kanton'),'094');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Živinice','75270', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Tuzlanski kanton'),'106');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Doboj-Istok','74101', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Tuzlanski kanton'),'128');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Sapna','75411', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Tuzlanski kanton'),'138');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Teočak','75414', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Tuzlanski kanton'),'147');

INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Breza','71370', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Zeničko-Dobojski kanton'),'010');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Kakanj','72240', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Zeničko-Dobojski kanton'),'043');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Maglaj','74250', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Zeničko-Dobojski kanton'),'060');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Olovo','71340', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Zeničko-Dobojski kanton'),'067');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Tešanj','74260', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Zeničko-Dobojski kanton'),'090');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Vareš','71330', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Zeničko-Dobojski kanton'),'096');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Visoko','71300', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Zeničko-Dobojski kanton'),'198');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Zavidovići','72220', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Zeničko-Dobojski kanton'),'102');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Zenica','72101', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Zeničko-Dobojski kanton'),'103');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Žepče','72230', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Zeničko-Dobojski kanton'),'105');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Doboj-Jug','74000', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Zeničko-Dobojski kanton'),'132');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Usora','74230', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Zeničko-Dobojski kanton'),'025');


INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Goražde','73101', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Bosansko-Podrinjski kanton'),'033');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Foča','73302', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Bosansko-Podrinjski kanton'),'134');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Pale','71420', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Bosansko-Podrinjski kanton'),'136');

INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Čapljina','88300', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Hercegovačko-neretvanski kanton'),'021');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Čitluk','88260', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Hercegovačko-neretvanski kanton'),'023');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Mostar','88000', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Hercegovačko-neretvanski kanton'),'180');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Jablanica','88420', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Hercegovačko-neretvanski kanton'),'041');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Konjic','88400', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Hercegovačko-neretvanski kanton'),'049');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Neum','88390', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Hercegovačko-neretvanski kanton'),'107');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Prozor-Rama','88440', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Hercegovačko-neretvanski kanton'),'073');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Ravno','88370', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Hercegovačko-neretvanski kanton'),'207');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Stolac','88360', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Hercegovačko-neretvanski kanton'),'086');

INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Široki Brijeg','88220', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Zapadnohercegovački  kanton'),'054');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Grude','88340', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Zapadnohercegovački  kanton'),'037');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Ljubuški','88320', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Zapadnohercegovački  kanton'),'059');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Posušje','88240', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Zapadnohercegovački  kanton'),'070');

INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Hadžići','71240', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Kanton Sarajevo'),'038');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Ilijaš','71380', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Kanton Sarajevo'),'040');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Centar Sarajevo','71000', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Kanton Sarajevo'),'077');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Ilidža','71210', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Kanton Sarajevo'),'078');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Novo Sarajevo','71000', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Kanton Sarajevo'),'079');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Vogošća','71320', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Kanton Sarajevo'),'080');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Novi Grad','71000', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Kanton Sarajevo'),'108');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Stari Grad','71000', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Kanton Sarajevo'),'109');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Trnovo','71220', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Kanton Sarajevo'),'093');

INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Livno','80101', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Kanton 10'),'055');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Tomislav-Grad','80240', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Kanton 10'),'028');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Kupres','80320', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Kanton 10'),'052');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Glamoč','80230', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Kanton 10'),'032');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Bosnsko Grahovo','80270', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Kanton 10'),'013');
INSERT INTO cities (name, postcode, country_id, canton_id, municipality_code) VALUES('Drvar','80260', (select id from countries where name = 'Bosna i Hercegovina'), (select id from cantons where name = 'Kanton 10'),'027');
