INSERT INTO job_types (name) VALUES
('Električar'),
('Moler'),
('Prenos stvari'),
('Cijepanje drva'),
('Vrtlar'),
('Krojač'),
('Frizer'),
('Kuhar'),
('Programer'),
('Građevinski radnik'),
('Vodoinstalater'),
('Stolar'),
('Medicinska sestra'),
('Veterinar'),
('Učitelj'),
('Fitness trener'),
('Fotograf'),
('Grafički dizajner'),
('Računovođa'),
('Arhitekt'),
('Dostavljač hrane'),
('Vozač taksija'),
('Ugostiteljski radnik'),
('Recepcionar'),
('Kasir'),
('Serviser računala'),
('Kozmetičarka'),
('Masovni terapeut'),
('Zidarski radnik'),
('Instalater grijanja'),
('Profesionalni čistač'),
('Održavanje vozila'),
('Pisanje sadržaja'),
('Planiranje događaja'),
('Konzultant za prodaju'),
('Sekretar'),
('Elektronički tehničar'),
('Održavanje zelenih površina'),
('Barmen'),
('Prodavač'),
('Dizajner interijera'),
('Automehaničar'),
('Pekar'),
('Vatrogasac'),
('Poljoprivrednik'),
('Građevinski nadzornik'),
('Dizajner modnih dodataka'),
('Fizički terapeut'),
('Arhivista'),
('Veterinarski tehničar'),
('Ljevač metala'),
('Medicinski tehničar'),
('Zubni tehničar'),
('Tehničar za klimatizaciju'),
('Plinska rukovoditeljica'),
('Obiteljski liječnik'),
('Psiholog'),
('Radiološki tehničar'),
('Građevinski nadzornik'),
('Vođa projekta'),
('Trgovac'),
('Trgovac nekretninama'),
('Šumar'),
('Gipsar'),
('Pekar'),
('Limenar'),
('Građevinski inženjer'),
('Vozač kamiona');
